### PR TITLE
Patch 1

### PR DESCRIPTION
**Pull request by bbrout**
This is a pull request for an online education project. I will try to update later if I can get a chance to get to it. This is part of the hackathon.

### CODE REVIEW

**Comment by jasonblais** [comment]
Thanks @bbrout!

**Comment by bbrout** [comment]
I believe these updates are included in the pull request and I do not have to create another pull request. I think.

**Comment by jasonblais** [comment]
Correct, thank you @bbrout!

**Comment by emilyacook** [comment]
Thank you @bbrout! Your submission has been recorded 🙌🏻

**Pull request merged**
